### ISSUE TITLE
Make inputTrees immutable

### ISSUE THREAD

**Issue by caitp** [broccolijs/broccoli-plugin#1]
When a plugin accepts multiple inputTrees, the inputTrees may be mutated outside of the stream of the build. This leads to instability which is difficult to manage, and it's a bit challenging to poke through a build and figure out why it's behaving in a weird way that it does.

A comment from https://github.com/angular/angular/pull/2064#issuecomment-109152724 should help to clarify why this is a problem.

An example fix for this (which would prevent code as linked above from being written in the first place):

``` js
function BasePluginClass(inputTrees, options) {
  if (Array.isArray(inputTrees)) {
    // No pushing/popping/splicing/etc, throw errors in strict mode when trying to adjust these
    Object.preventExtensions(inputTrees);
    Object.defineProperty(this, "inputTrees", readOnlyNonConfigurable(inputTrees));
  } else {
    Object.defineProperty(this, "inputTree", readOnlyNonConfigurable(inputTrees));
  }
  // ... whatever else
}
```

Maybe there's a better way to do this to give a hint to make sure we don't write broccoli scripts in stupid ways, or something, but this is the first thing that comes to mind.

This is related to the mutable outputPath issue discussed previously, but is somewhat different in practice.

**Comment by joliss** [comment]
Yes, trees are definitely supposed to be immutable, and we're not enforcing that at the moment.

@stefanpenner mentioned some use cases where Ember CLI addons want to modify the set of `inputTrees` at initialization time (when `Brocfile.js` runs basically, so before the Broccoli builder kicks in). I'm still unsure - we could allow early mutation and then freeze it, or maybe we should find a different approach and really have trees be completely immutable. /cc @rwjblue

**Comment by caitp** [comment]
Allowing early mutations would be acceptable once outputPaths are fully immutable (the other issue), but I think it still produces code which more difficult to reason about than it should be

**Comment by stefanpenner** [comment]
Cc @chadhietala

**Comment by stefanpenner** [comment]
This has gone stale, I believe our current architecture addresses many of these concerns.
