### ISSUE TITLE
got [object Object] for inputNodes[1]

### ISSUE THREAD

**Issue by poplevente** [broccolijs/broccoli-plugin#26]
Hi Guys,

since the last update we get 
BroccoliMergeTrees (TreeMerger (lint app)): Expected Broccoli node, got [object Object] for inputNodes[1]

not sure if it's related to the last update or not, did anyone encouter the same? any reason this might happen?

**Comment by poplevente** [comment]
an ugly fix is to manually go back to the previous version of this plugin, but this required changes within our automatic build, etc. would be nice to correct in a short time ...

**Comment by rwjblue** [comment]
This seems effectively the same as https://github.com/broccolijs/broccoli-merge-trees/issues/65, can you confirm? And also confirm that that solution fixed things for you?

**Comment by ljmerza** [comment]
The issue was solved for me thank you.

**Comment by rwjblue** [comment]
Thank you for confirming (and sorry for the problems), I'm going to close for now though I'm happy to reopen if there are still other issues...

**Comment by poplevente** [comment]
i still get an error, this time the inputNodes issues is gone, but i get an Invalid tree found.
the fix is the same if i revert the broccoli-plugin to version 1.3.0, then it's okay.
