### ISSUE TITLE
cachePath persistence.

### ISSUE THREAD

**Issue by blackening** [broccolijs/broccoli-plugin#5]
According to documentation:
"this.cachePath: The path on disk to an auxiliary cache directory. Use this to store files that you want preserved between builds. This directory will only be deleted when Broccoli exits."

Is it possible to preserve cachePath between without watching?

**Comment by joliss** [comment]
Not at the moment. It's under discussion to add this in the future, and I'd like to see it, but there's a few technical issues to be worked out first.

**Comment by joliss** [comment]
We now have an open issue on the Broccoli core repo with some notes: https://github.com/broccolijs/broccoli/issues/282
