### ISSUE TITLE
tests appear to require the internet

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli-plugin#6]
this isn't ideal with slow/non-existent net. Is it possible for it not to rely on it, or maybe have an offline mode?

**Comment by joliss** [comment]
We need to download multiple versions of Broccoli. (At the moment it's just one, but soon it'll be more.) I couldn't come up with a better way to do this, like going directly through npm, so ended up with a [shell script](https://github.com/broccolijs/broccoli-plugin/blob/master/test/install_dependencies.sh).

If you want to avoid redownloading when rerunning the tests, you can run `mocha`, by the way.

**Comment by stefanpenner** [comment]
> We need to download multiple versions of Broccoli. (At the moment it's just one, but soon it'll be more.) I couldn't come up with a better way to do this, like going directly through npm, so ended up with a shell script.

it would be handy (and speed up re-running of tests) if by default it reused existing versions, and only downloaded missing.

**Comment by joliss** [comment]
Sounds useful - done :)

**Comment by stefanpenner** [comment]
:+1: being on slow internets reminds of such things.
